### ISSUE TITLE
Umple code generation in Orion

### ISSUE THREAD

**Issue by vtrlx** [umple/umple.orion#1]
An IDE for Umple isn't exactly useful if code can't be compiled. So, the plugin should provide facilities to compile Umple code into a user's project.

Preferably:
- [x] Connect the compiler to Orion
- [x] Add a button to generate code
- [x] Add a menu to generate code
- [x] Add a context menu (on a file) to generate code
- [x] Add a keyboard shortcut to generate code

**Comment by vtrlx** [comment]
As @TimLethbridge commented in #3, my implementation for this issue will focus on connecting Orion to UmpleOnline's compiler. It will simply be a GET request to UmpleOnline's compiler script at http://cruise.eecs.uottawa.ca/umpleonline/scripts/compiler.php.

This will allow users of any Orion server to compile Umple code without the server needing to be running Umple, and it allows the plugin to leverage UmpleOnline's central nature to it's benefit (I.E, if the compiler on Cruise updates, then so too will the compiler that Orion uses). 

Seeing as it's already the suggestion for graph displaying, I've already gotten started with getting it implemented in Orion. I hope to have something working and committed by the end of next week.

**Comment by vtrlx** [comment]
Determination.

![Success](https://cloud.githubusercontent.com/assets/8976090/13414917/4dedb790-df24-11e5-8c48-43ca73a9a717.png)

**Comment by Nava2** [comment]
Nice! That's awesome. :+1:

**Comment by vahdat-ab** [comment]
@nwam I wonder if you got sth so far or not?
