### ISSUE TITLE
Plugin is not able to generate the code and refresh the pager because of HTTP

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple.orion#10]
When users want to generate the code, the browser blocks the connection to Umple server because an HTTP connection is created inside an https connection.

**Comment by vahdat-ab** [comment]
these two links might be useful:
http://stackoverflow.com/questions/26285539/since-v38-chrome-extension-cannot-load-from-http-urls-anymore-workaround
http://stackoverflow.com/questions/7699615/cross-domain-xmlhttprequest-using-background-pages/7699773#7699773

**Comment by nwam** [comment]
Instead of modifying the inner-workings of the plugin, I resolved the issue by modifying the umple-orion-server. Specifically, I added a keystore and enabled HTTPS/SSL on the server.
